export const FETCH_SELLER_LIST = 'FETCH_SELLER_LIST';
export const FETCH_GOODS_LIST = 'FETCH_GOODS_LIST';
export const RESET_SHOPPING_LIST = 'RESET_SHOPPING_LIST';
export const SET_FOOD_COUNT = 'SET_FOOD_COUNT';
