export const RECEIVE_SELLER_LIST = 'RECEIVE_SELLER_LIST';
export const RECEIVE_GOODS_LIST = 'RECEIVE_GOODS_LIST';
export const RECEIVE_RATINGS_LIST = 'RECEIVE_RATINGS_LIST';
export const RESET_SHOPPING_LIST = 'RESET_SHOPPING_LIST';
export const SET_FOOD_COUNT = 'SET_FOOD_COUNT';
